services:
  # Your NestJS application
  app-prod:
    build:
      context: .
      target: production
    restart: unless-stopped
    depends_on:
      - pgsql
      - redis
    ports:
      - '${APP_PORT:-3000}:3000'
    environment:
      - NODE_ENV=production
      - DB_HOST=pgsql
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - REDIS_URL=redis://redis:6379
    networks:
      - connect_crm_network
    # Optional: add healthcheck
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3

  adminer:
    image: adminer
    restart: always
    depends_on:
      - pgsql
    ports:
      - 8080:8080
    networks:
      - connect_crm_network

  pgsql:
    image: 'postgres:17-alpine3.22'
    restart: always
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - connect_crm:/var/lib/postgresql/data
    networks:
      - connect_crm_network

  redis:
    image: 'redis:6.2.19-alpine'
    ports:
      - '6379:6379'
    networks:
      - connect_crm_network

volumes:
  connect_crm:

networks:
  connect_crm_network:
    driver: bridge
